<?php

namespace DiabeteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DiabeteProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiabeteProfileRepository extends EntityRepository
{
}
