<?php

namespace DiabeteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MesureactiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesureactiviteRepository extends EntityRepository
{
	public function getMesureActivite(Subscriber $subscriber, $nbDays) {
		$now = new \DateTime();
		$nbDaysAgo = new \DateTime("-{$nbDays} days");

		$qb = $this->createQueryBuilder('btd')
						->where('btd.idAbonne = :subscriber')
						->andWhere('btd.dateDebut BETWEEN :nbDaysAgo AND :now')
						->setParameter('subscriber', $subscriber)
						->setParameter('nbDaysAgo', $nbDaysAgo)
						->setParameter('now', $now)
						->orderBy('btd.dateDebut','desc');
		return $qb->getQuery()->getResult();
	}
}